### ISSUE TITLE
Jobs cannot survive a process restart

### ISSUE THREAD

**Issue by kirbysayshi** [juliangruber/level-schedule#5]
Hey, thanks for writing this package. I think I've found a bug. Within the `start` method (https://github.com/juliangruber/level-schedule/blob/cbf143d7b03ee154273e8ef7d9e0e5a96d1e470e/index.js#L101), the `_jobs` key is checked for the actual callback. If the process is restarted after a job is queued but before it has executed, then the `_jobs` object will be empty even though a `task` still exists in the db.

When I restart my process once it in this state it immediately dies with a `job not found` error for this reason.

Maybe I'm doing something wrong? But it seems like the task payload can survive a restart, but not the task executor itself.

**Comment by kirbysayshi** [comment]
This is reproducible with the following script:

```js
// schedule-bug.js
var level = require('level');

var db = level('/tmp/scheduler-test', {
  createIfMissing: true,
  valueEncoding: 'json'
});

var jobsDB = require('level-schedule')(db);
var jobkey = 'immajob!what';

if (process.env.INIT) {
  jobsDB
  .job(jobkey, function(_, done) {
    console.log('JOB RUN GO!');
    done(null);
  })
  .run(jobkey, Date.now() + 10000);

  console.log('ctrl+c the process quickly!');
}
```

And then first run it with:

```sh
$ INIT=yeah node schedule-bug.js
```
(ctrl+c)

```sh
$ node schedule-bug.js
```
```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: job not found
    at /Users/drew/Dropbox/js/question-book/node_modules/level-schedule/index.js:107:17
    at /Users/drew/Dropbox/js/question-book/node_modules/level-schedule/node_modules/level-peek/index.js:36:12
    at ReadStream.onEvent (/Users/drew/Dropbox/js/question-book/node_modules/level-schedule/node_modules/level-peek/index.js:12:10)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (/Users/drew/Dropbox/js/question-book/node_modules/level/node_modules/level-packager/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at ReadStream.Readable.push (/Users/drew/Dropbox/js/question-book/node_modules/level/node_modules/level-packager/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at /Users/drew/Dropbox/js/question-book/node_modules/level/node_modules/level-packager/node_modules/levelup/node_modules/level-iterator-stream/index.js:40:12
    at /Users/drew/Dropbox/js/question-book/node_modules/level/node_modules/level-packager/node_modules/levelup/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-iterator.js:24:16
    at /Users/drew/Dropbox/js/question-book/node_modules/level/node_modules/leveldown/node_modules/abstract-leveldown/abstract-iterator.js:24:16
```

**Comment by kirbysayshi** [comment]
I suppose the "bug" is more that if you don't redefine the job before `peek()` calls back (so within the same tick as startup), then there is no job to execute.

**Comment by kirbysayshi** [comment]
Ok, I guess I was using the package wrongly. I'm sorry for misunderstanding. You have to define your job generically, and use the payload to parameterize it, instead of writing a custom job for each task.

Sorry!
